---

- name: write values template
  copy:
    content: |
      {{ manifest_file }}
    dest:  /tmp/manifest_{{ name }}-template.txt

- name: compile values
  template:
    src:  /tmp/manifest_{{ name }}-template.txt
    dest: /tmp/manifest_{{ name }}.yml

- name: kube create
  command: kube apply -f /tmp/manifest_{{ name }}.yml
